name: pushover-client
version: '0.1.0.0'
category: Network
author: Patrick Brisbin
maintainer: pbrisbin@gmail.com
copyright: 2017 pbrisbin@gmail.com
license: MIT
github: pbrisbin/pushover-client
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Pushover.Client
  - Pushover.Client.Credentials
  - Pushover.Client.Device
  - Pushover.Client.HTTP
  - Pushover.Client.Login
  - Pushover.Client.Message
  - Pushover.Client.Options
  - Pushover.Client.Response
  dependencies:
  - base >=4.7 && <5
  - aeson
  - bytestring
  - directory
  - exceptions
  - filepath
  - http-client
  - http-client-tls
  - optparse-applicative
  - text
  - xdg-basedir
executables:
  pushover-client:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - pushover-client
    - aeson
    - bytestring
    - text
